// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";
// import SessionWrapper from "./components/SessionWrapper";
// import Script from "next/script";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Grand Finale project",
//   description: "Generated by create Shyam",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <SessionWrapper>
//         <Navbar />
//         {children}
//         </SessionWrapper>
//       </body>
//     </html>
//   );
// }
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";
// import SessionWrapper from "./components/SessionWrapper";
// import Script from "next/script";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Grand Finale project",
//   description: "Generated by create Shyam",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {/* 🔹 Google Translate Dropdown */}
//         <div
//           id="google_translate_element"
//           style={{
//             position: "fixed",
//             top: "10px",
//             right: "10px",
//             zIndex: 9999,
//           }}
//         ></div>

//         <SessionWrapper>
//           <Navbar />
//           {children}
//         </SessionWrapper>

//         {/* 🔹 Google Translate Scripts */}
//         <Script
//           src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
//           strategy="afterInteractive"
//         />

//         <Script id="google-translate-init" strategy="afterInteractive">
//           {`
//             function googleTranslateElementInit() {
//               new google.translate.TranslateElement(
//                 { pageLanguage: 'en' },
//                 'google_translate_element'
//               );
//             }
//           `}
//         </Script>
//       </body>
//     </html>
//   );
// }
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";
// import SessionWrapper from "./components/SessionWrapper";
// import Script from "next/script";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// export const metadata = {
//  title: "Grand Finale project",
//    description: "Generated by create Shyam",
//  };
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <SessionWrapper>
//           <Navbar />
//           {children}
//         </SessionWrapper>

//         {/* Google Translate Script */}
//         <Script
//           src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
//           strategy="afterInteractive"
//         />

//         <Script id="google-translate-init" strategy="afterInteractive">
//           {`
//             function googleTranslateElementInit() {
//               new google.translate.TranslateElement(
//                 {
//                   pageLanguage: 'en',
//                   autoDisplay: false
//                 },
//                 'google_translate_element'
//               );
//             }
//           `}
//         </Script>
//       </body>
//     </html>
//   );
// }
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import SessionWrapper from "./components/SessionWrapper";
import Script from "next/script";
import Providers from "./providers";   // ✅ ADD THIS

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Grand Finale project",
  description: "Generated by create Shyam",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning> {/* ✅ ADD THIS */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased transition-colors duration-300`}
      >
        <Providers> {/* ✅ WRAP ONLY ONCE */}
          <SessionWrapper>
            <Navbar />
            {children}
          </SessionWrapper>
        </Providers>

        {/* Google Translate Script */}
        <Script
          src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
          strategy="afterInteractive"
        />

        <Script id="google-translate-init" strategy="afterInteractive">
          {`
            function googleTranslateElementInit() {
              new google.translate.TranslateElement(
                {
                  pageLanguage: 'en',
                  autoDisplay: false
                },
                'google_translate_element'
              );
            }
          `}
        </Script>
      </body>
    </html>
  );
}
